services:
  postgres:
    container_name: ms-services
    image: postgres:latest
    environment:
      POSTGRES_USER: embarkx
      POSTGRES_PASSWORD: embarkx
      POSTGRES_DB: jobapp_db   # main DB
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - postgres


  zipkin:
    container_name: ms-services-zipkin
    image: openzipkin/zipkin:latest
    ports:
      - 9411:9411  # Zipkin UI and API
    restart: unless-stopped
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

