spring:
  application:
    name: companyms

  datasource:
    url: jdbc:postgresql://localhost:5432/company_db
    username: embarkx
    password: embarkx

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081



